package com.rehome.chatnotificationservice.enums;

public enum NotificationType {

    // Member
    NEW_CHAT_MESSAGE,
    CONSIGNMENT_FORM_REVIEWED,
    CONSIGNMENT_FORM_EXPIRING,
    CONSIGNMENT_RECEIPT_PENDING_CONFIRM,
    PRODUCT_LISTED,
    PRODUCT_SOLD,
    CONSIGNMENT_TERM_EXPIRING,
    ITEM_WITHDRAWAL_REQUESTED,
    ORDER_STATUS_CHANGED,
    RETURN_REFUND_RESULT,
    WITHDRAWAL_RESULT,
    BANK_ACCOUNT_VERIFICATION_RESULT,
    ITEM_FLAGGED_COUNTERFEIT,
    DONATION_RECEIVED,
    DONATION_CAMPAIGN_EXPIRING,
    NEW_POST_FROM_FOLLOWED_ORG,
    VIOLATION_REPORT_RESULT,

    // Organization
    NEW_DONATION_REGISTRATION,
    ORG_VERIFICATION_RESULT,
    LEGAL_INFO_CHANGE_RESULT,
    CAMPAIGN_HIDDEN_OR_CLOSED,
    CONTENT_REMOVED,

    // Moderator
    NEW_CONSIGNMENT_FORM,
    ORDER_NEEDS_PACKING,
    RETURN_REQUESTED,
    RETURNED_ITEM_ARRIVED,
    REFUND_PENDING,
    WITHDRAWAL_REQUEST_PENDING,
    NEW_ORG_PROFILE,
    LEGAL_INFO_CHANGE_REQUEST,
    NEW_VIOLATION_REPORT,
    CLAIMED_TASK_EXPIRING,

    // Admin
    QUEUE_TASK_OVERDUE

}
